List.apply(1, 2, 3)
List.range(1,5)
List.range(1,9,3)
List.range(9, 1, -3)
List.fill(5)('a')
List.fill(2, 3)('b')
List.tabulate(5)(n=>n*n)
List.concat(List('a', 'b'), List('c'))
(List(1,2), List(5,5,6)).zipped.map(_*_)
(List("abc", "de"), List(3, 2)).zipped.forall(_.length == _)
(List("abc", "dea"), List(3, 2)).zipped.exists(_.length != _)